### PR TITLE
Added built-in launch artifacts extension

### PR DESCRIPTION
**Pull request by nvborisenko**
Now it is possible to:
```
rp_launch_artifacts = *.png; some/path/*.log
```

where base directory is a project dir.

### CODE REVIEW

**Comment by PiotrNestor** [comment]
@nvborisenko 
We can test this feature when it's merged and released ...

**Comment by nvborisenko** [comment]
@PiotrNestor released, please help to verify: https://github.com/reportportal/agent-net-gauge/releases/tag/1.17.0

**Comment by PiotrNestor** [comment]
@nvborisenko
I'm not getting the artifacts attached on the test launch level ...

I've tried the following in gauge env/default/default.properies:
```
rp_launch_artifacts = reports/*.log, *.json, env/default/*.properties
ReportPortal_launch_artifacts = reports/*.log, *.json, env/default/*.properties
```

I have: reportportal (1.17.0)

**Comment by nvborisenko** [comment]
```
rp_launch_artifacts = *.png; some/path/*.log
```

Pay attention on `;` as a delimiter

**Comment by PiotrNestor** [comment]
@nvborisenko 
OK. The ';' delimiter was the trick. I've missed that.
Now It's working to get the artifacts

When opening 'Log View' I cane see the attached files and it's possible to access them.

When clicking on 'Log View': I'm also getting: An error occurred while connecting to server: Test Item '244' not found. Did you use correct Test Item ID?
The same error is displayed when opening 'Log View' with not attached artifacts.

**Comment by nvborisenko** [comment]
Feel free to post an issue https://github.com/reportportal/reportportal

Thank you for confirming it works.

**Pull request merged**
